// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsvluvbwzcmmtglqtawt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzdmx1dmJ3emNtbXRnbHF0YXd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTUwMzMsImV4cCI6MjA3MjU5MTAzM30.FaqaTQ967mL5IfgDH8auAMhnOKM4QNUHt2_FE6DBW7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});